import {
  AlertTriangle,
  ArrowDownToLine,
  Banknote,
  BookOpen,
  Building2,
  CircleDollarSign,
  CheckCircle2,
  CircleSlash,
  Coins,
  CreditCard,
  Fingerprint,
  FileText,
  GraduationCap,
  Handshake,
  IdCard,
  KeyRound,
  Landmark,
  Laptop,
  Lock,
  LineChart,
  MapPin,
  Nfc,
  PiggyBank,
  Receipt,
  Search,
  Send,
  QrCode,
  Repeat,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Signal,
  Smartphone,
  Sprout,
  Store,
  Tractor,
  UserCheck,
  TrendingUp,
  Users,
  Wallet,
  Wifi,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon registry.
 *
 * Server Components cannot pass component references across the client
 * boundary, so anything that hands an icon to a Client Component passes one of
 * these names instead and the icon is resolved on the client side.
 */
export const ICONS = {
  alert: AlertTriangle,
  banknote: Banknote,
  checkCircle: CheckCircle2,
  deposit: ArrowDownToLine,
  bookOpen: BookOpen,
  building: Building2,
  circleSlash: CircleSlash,
  coins: Coins,
  creditCard: CreditCard,
  dollar: CircleDollarSign,
  fileText: FileText,
  fingerprint: Fingerprint,
  graduation: GraduationCap,
  handshake: Handshake,
  idCard: IdCard,
  key: KeyRound,
  landmark: Landmark,
  lock: Lock,
  laptop: Laptop,
  lineChart: LineChart,
  mapPin: MapPin,
  nfc: Nfc,
  piggyBank: PiggyBank,
  receipt: Receipt,
  search: Search,
  send: Send,
  qrCode: QrCode,
  repeat: Repeat,
  scale: Scale,
  shield: ShieldCheck,
  shoppingBag: ShoppingBag,
  signal: Signal,
  smartphone: Smartphone,
  sprout: Sprout,
  store: Store,
  tractor: Tractor,
  userCheck: UserCheck,
  trendingUp: TrendingUp,
  users: Users,
  wallet: Wallet,
  wifi: Wifi,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
